### ISSUE TITLE
eslint version security issue

### ISSUE THREAD

**Issue by acroswel** [eplatallc/dev-test#1]
github has a security alert about the eslint version being used in this project. @toddtarsi you were the last one to commit here but it was way back in 2017, are we even using this repo?

**Comment by toddtarsi** [comment]
@acroswel - We recommend a lot of the interviewees we send back to use this as a sample codebase to brush up on their skills. Other than that, no.

**Comment by acroswel** [comment]
Should we bump the eslint version to clear the security alert?

**Comment by doverdb12** [comment]
Updated. Thanks. 👍

**Comment by acroswel** [comment]
Thanks @doverdb !
